# filename: app.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import re
import tempfile
from pathlib import Path

import pandas as pd
import streamlit as st

try:
    import pythoncom
except Exception:
    pythoncom = None

try:
    import win32com.client as win32
except Exception:
    win32 = None


st.set_page_config(page_title="Contractor Onboarding Automation", layout="wide")

st.markdown(
    """
    <style>
    .stApp { background: #F6F7F8; color: #1A1A1A; }
    .block-container { padding-top: 1.2rem; padding-bottom: 2rem; }
    h1,h2,h3,h4,h5,h6,p,div,span,label,li { color: #1A1A1A !important; }
    .banner {
        background: #0A0A0A;
        border-left: 6px solid #86BC25;
        color: #FFFFFF !important;
        padding: 18px 20px;
        border-radius: 10px;
        margin-bottom: 16px;
    }
    .banner * { color: #FFFFFF !important; }
    .card {
        background: #FFFFFF;
        border: 1px solid #E6E6E6;
        border-radius: 10px;
        padding: 14px 16px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        margin-bottom: 14px;
    }
    .metric-value {
        font-size: 28px;
        font-weight: 700;
        color: #0A0A0A !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

OWNER_REQUIRED = {"system id", "approver", "approver id"}
ONBOARDING_REQUIRED = {
    "contractor name",
    "contractor email",
    "manager name",
    "manager email",
    "team",
    "start date",
    "end date",
    "requested systems",
    "request id",
    "business justification",
}
ROLE_REQUIRED = {"team", "system", "role type", "role name", "role description"}


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out.columns = [
        str(c).strip().lower().replace("_", " ").replace("\n", " ")
        for c in out.columns
    ]
    return out


def read_table(uploaded_file) -> pd.DataFrame:
    if uploaded_file is None:
        return pd.DataFrame()
    try:
        uploaded_file.seek(0)
        df = pd.read_csv(uploaded_file)
        return normalize_columns(df)
    except Exception:
        uploaded_file.seek(0)
        df = pd.read_excel(uploaded_file)
        return normalize_columns(df)


def clean_text(value) -> str:
    return "" if pd.isna(value) else str(value).strip()


def split_systems(value) -> list[str]:
    raw = clean_text(value).upper()
    items = re.split(r"[,\n;/]+", raw)
    return [item.strip() for item in items if item.strip()]


def validate_columns(df: pd.DataFrame, required: set[str], label: str) -> list[str]:
    missing = sorted(required - set(df.columns))
    return [f"{label}: missing columns -> {', '.join(missing)}"] if missing else []


def fix_manager_swap(row: pd.Series) -> tuple[pd.Series, str]:
    row = row.copy()
    manager_name = clean_text(row.get("manager name"))
    manager_email = clean_text(row.get("manager email"))
    if "@" in manager_name and "@" not in manager_email:
        row["manager name"], row["manager email"] = manager_email, manager_name
        return row, "Manager Name and Manager Email were swapped and auto-corrected."
    return row, ""


def role_filter(role_rows: pd.DataFrame, desired_df: pd.DataFrame, system_id: str) -> pd.DataFrame:
    if role_rows.empty or desired_df.empty:
        return role_rows
    if not {"system", "role", "role type"}.issubset(desired_df.columns):
        return role_rows

    desired = desired_df.copy()
    desired["system"] = desired["system"].astype(str).str.strip().str.upper()
    desired["role"] = desired["role"].astype(str).str.strip().str.upper()
    desired["role type"] = desired["role type"].astype(str).str.strip().str.upper()
    desired = desired[desired["system"] == system_id]

    if desired.empty:
        return role_rows

    roles = role_rows.copy()
    roles["role name"] = roles["role name"].astype(str).str.strip().str.upper()
    roles["role type"] = roles["role type"].astype(str).str.strip().str.upper()

    merged = roles.merge(
        desired[["system", "role", "role type"]],
        left_on=["system", "role name", "role type"],
        right_on=["system", "role", "role type"],
        how="inner",
    )
    return merged[role_rows.columns] if not merged.empty else role_rows.iloc[0:0]


def process_inputs(owners_df, onboarding_df, roles_df, desired_df):
    owners = owners_df.copy()
    owners["system id"] = owners["system id"].astype(str).str.strip().str.upper()
    owners["approver"] = owners["approver"].astype(str).str.strip()
    owners["approver id"] = owners["approver id"].astype(str).str.strip().str.lower()

    roles = roles_df.copy()
    roles["team"] = roles["team"].astype(str).str.strip().str.upper()
    roles["system"] = roles["system"].astype(str).str.strip().str.upper()
    roles["role type"] = roles["role type"].astype(str).str.strip().str.upper()
    roles["role name"] = roles["role name"].astype(str).str.strip()

    desired = desired_df.copy()
    if not desired.empty:
        desired = normalize_columns(desired)

    draft_rows, role_rows, exception_rows = [], [], []

    for idx, source_row in onboarding_df.iterrows():
        row, fix_note = fix_manager_swap(source_row)
        request_id = clean_text(row.get("request id")) or f"REQ-{idx+1:03d}"
        contractor = clean_text(row.get("contractor name"))
        contractor_email = clean_text(row.get("contractor email"))
        manager_name = clean_text(row.get("manager name"))
        manager_email = clean_text(row.get("manager email"))
        team = clean_text(row.get("team")).upper()
        start_date = row.get("start date")
        end_date = row.get("end date")
        justification = clean_text(row.get("business justification"))
        systems = split_systems(row.get("requested systems"))

        base = {
            "request id": request_id,
            "contractor name": contractor,
            "contractor email": contractor_email,
            "manager name": manager_name,
            "manager email": manager_email,
            "team": team,
            "start date": start_date,
            "end date": end_date,
            "business justification": justification,
        }

        if fix_note:
            exception_rows.append({
                "request id": request_id,
                "system": "",
                "issue type": "DATA_FIX",
                "issue": fix_note,
                "owner email": "",
                "action": "Review the source row.",
            })

        if not systems:
            exception_rows.append({
                "request id": request_id,
                "system": "",
                "issue type": "NO_SYSTEMS",
                "issue": "Requested Systems is blank.",
                "owner email": "",
                "action": "Populate Requested Systems.",
            })
            continue

        for system_id in systems:
            owner_match = owners[owners["system id"] == system_id]
            if owner_match.empty:
                exception_rows.append({
                    "request id": request_id,
                    "system": system_id,
                    "issue type": "OWNER_NOT_FOUND",
                    "issue": f"No owner found for {system_id}.",
                    "owner email": "",
                    "action": "Add this system to the owner file.",
                })
                continue

            owner_name = clean_text(owner_match["approver"].iloc[0])
            owner_email = clean_text(owner_match["approver id"].iloc[0])

            draft_rows.append({
                **base,
                "system": system_id,
                "owner name": owner_name,
                "owner email": owner_email,
            })

            matched_roles = roles[(roles["team"] == team) & (roles["system"] == system_id)]
            matched_roles = role_filter(matched_roles, desired, system_id)

            if matched_roles.empty:
                exception_rows.append({
                    "request id": request_id,
                    "system": system_id,
                    "issue type": "ROLE_NOT_FOUND",
                    "issue": f"No role mapping found for Team={team} and System={system_id}.",
                    "owner email": owner_email,
                    "action": "Review the role consolidated file.",
                })
            else:
                for _, r in matched_roles.iterrows():
                    role_rows.append({
                        **base,
                        "system": system_id,
                        "owner name": owner_name,
                        "owner email": owner_email,
                        "role type": clean_text(r.get("role type")),
                        "role name": clean_text(r.get("role name")),
                        "role description": clean_text(r.get("role description")),
                    })

    return pd.DataFrame(draft_rows), pd.DataFrame(role_rows), pd.DataFrame(exception_rows)


def build_attachment(owner_email, request_id, request_rows, role_rows, exception_rows):
    safe_owner = owner_email.replace("@", "_at_").replace(".", "_")
    safe_req = re.sub(r"[^A-Za-z0-9]+", "_", request_id).strip("_")
    out_dir = Path(tempfile.mkdtemp(prefix=f"onboarding_{safe_owner}_{safe_req}_"))
    file_path = out_dir / f"{safe_req}_RoleDetails.xlsx"

    summary = request_rows.copy()
    summary = summary.rename(columns={
        "request id": "Request ID",
        "contractor name": "Contractor Name",
        "contractor email": "Contractor Email",
        "manager name": "Manager Name",
        "manager email": "Manager Email",
        "team": "Team",
        "start date": "Start Date",
        "end date": "End Date",
        "system": "System",
        "business justification": "Business Justification",
    })

    if role_rows.empty:
        role_sheet = pd.DataFrame([{
            "System": ", ".join(sorted(request_rows["system"].dropna().astype(str).unique())),
            "Role": "No mapped role found",
            "Role type": "",
            "Comments": "No role mapping available for this request.",
        }])
    else:
        role_sheet = role_rows.copy()[["system", "role name", "role type", "role description"]]
        role_sheet = role_sheet.rename(columns={
            "system": "System",
            "role name": "Role",
            "role type": "Role type",
            "role description": "Comments",
        })

    with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
        summary.to_excel(writer, sheet_name="Request Summary", index=False)
        role_sheet.to_excel(writer, sheet_name="Role Details", index=False)

    return str(file_path)


def create_drafts(draft_df, role_df, exception_df):
    if draft_df.empty:
        return pd.DataFrame([{
            "request id": "",
            "owner email": "",
            "systems": "",
            "status": "Skipped",
            "details": "No owner-mapped requests were found.",
            "attachment": "",
        }])

    if pythoncom is None or win32 is None:
        return pd.DataFrame([{
            "request id": "",
            "owner email": "",
            "systems": "",
            "status": "Failed",
            "details": "pywin32 is unavailable.",
            "attachment": "",
        }])

    status_rows = []
    try:
        pythoncom.CoInitialize()
        outlook = win32.Dispatch("Outlook.Application")

        for (request_id, owner_email), owner_requests in draft_df.groupby(["request id", "owner email"], dropna=False):
            owner_name = clean_text(owner_requests["owner name"].iloc[0])
            systems = ", ".join(sorted(owner_requests["system"].dropna().astype(str).unique()))
            contractor = clean_text(owner_requests["contractor name"].iloc[0])
            contractor_email = clean_text(owner_requests["contractor email"].iloc[0])
            manager_name = clean_text(owner_requests["manager name"].iloc[0])
            manager_email = clean_text(owner_requests["manager email"].iloc[0])
            team = ", ".join(sorted(owner_requests["team"].dropna().astype(str).unique()))
            justification = clean_text(owner_requests["business justification"].iloc[0])

            owner_roles = role_df[
                (role_df["request id"] == request_id) & (role_df["owner email"] == owner_email)
            ] if not role_df.empty else pd.DataFrame()

            owner_exceptions = exception_df[
                (exception_df["request id"] == request_id)
            ] if not exception_df.empty else pd.DataFrame()

            attachment = build_attachment(owner_email, str(request_id), owner_requests, owner_roles, owner_exceptions)

            body = "\n".join([
                f"Hello {owner_name or 'System Owner'},",
                "",
                "Approval is requested for the contractor onboarding access request below.",
                "",
                f"Request ID: {request_id}",
                f"Contractor Name: {contractor}",
                f"Contractor Email: {contractor_email}",
                f"Manager Name: {manager_name}",
                f"Manager Email: {manager_email}",
                f"Team: {team}",
                f"Requested System(s): {systems}",
                f"Business Justification: {justification}",
                "",
                "To understand the requested roles, please refer to the attached workbook.",
                "",
                "Please review and provide your approval.",
                "",
                "Thank you.",
            ])

            try:
                mail = outlook.CreateItem(0)
                mail.To = owner_email
                mail.Subject = f"Approval required | Contractor onboarding | {request_id} | {systems}"
                mail.Body = body
                mail.Attachments.Add(attachment)
                mail.Save()

                status_rows.append({
                    "request id": request_id,
                    "owner email": owner_email,
                    "systems": systems,
                    "status": "Draft created",
                    "details": "Saved in Outlook Drafts successfully.",
                    "attachment": Path(attachment).name,
                })
            except Exception as exc:
                status_rows.append({
                    "request id": request_id,
                    "owner email": owner_email,
                    "systems": systems,
                    "status": "Failed",
                    "details": f"Draft creation failed: {exc}",
                    "attachment": Path(attachment).name,
                })
    except Exception as exc:
        status_rows.append({
            "request id": "",
            "owner email": "",
            "systems": "",
            "status": "Failed",
            "details": f"Outlook could not be opened: {exc}",
            "attachment": "",
        })
    finally:
        if pythoncom is not None:
            try:
                pythoncom.CoUninitialize()
            except Exception:
                pass

    return pd.DataFrame(status_rows)


def metric_card(col, label, value):
    with col:
        st.markdown(
            f"<div class='card'><strong>{label}</strong><br><span class='metric-value'>{value}</span></div>",
            unsafe_allow_html=True,
        )


st.markdown(
    """
    <div class="banner">
        <h2 style="margin:0;">Contractor Onboarding Automation</h2>
        <p style="margin:8px 0 0 0;">Creates Outlook drafts for the <strong>system owner</strong> and attaches a role-details workbook.</p>
    </div>
    """,
    unsafe_allow_html=True,
)

with st.expander("How it works", expanded=True):
    st.markdown(
        """
        1. Upload the four Excel files.
        2. The app splits Requested Systems into individual system IDs.
        3. Each system is matched to the system owner file.
        4. Role rows are filtered by Team + System.
        5. One Outlook draft is created per request + owner.
        """
    )

c1, c2 = st.columns(2)
with c1:
    owner_file = st.file_uploader("System owner file", type=["xlsx", "csv"])
    onboarding_file = st.file_uploader("Onboarding form", type=["xlsx", "csv"])
with c2:
    role_file = st.file_uploader("Role consolidated file", type=["xlsx", "csv"])
    desired_file = st.file_uploader("Desired outcome file (optional)", type=["xlsx", "csv"])

show_debug = st.checkbox("Show debug details", value=True)
run = st.button("Process requests and create Outlook drafts", type="primary")

if run:
    if owner_file is None or onboarding_file is None or role_file is None:
        st.error("Please upload the System owner, Onboarding, and Role consolidated files.")
        st.stop()

    owners_df = read_table(owner_file)
    onboarding_df = read_table(onboarding_file)
    roles_df = read_table(role_file)
    desired_df = read_table(desired_file) if desired_file else pd.DataFrame()

    errors = []
    errors.extend(validate_columns(owners_df, OWNER_REQUIRED, "System owner file"))
    errors.extend(validate_columns(onboarding_df, ONBOARDING_REQUIRED, "Onboarding form"))
    errors.extend(validate_columns(roles_df, ROLE_REQUIRED, "Role consolidated file"))

    if errors:
        st.error("Input validation failed.")
        for err in errors:
            st.write(f"- {err}")
        st.stop()

    draft_df, role_df, exception_df = process_inputs(owners_df, onboarding_df, roles_df, desired_df)
    status_df = create_drafts(draft_df, role_df, exception_df)

    a, b, c, d = st.columns(4)
    metric_card(a, "Owner-mapped rows", len(draft_df))
    metric_card(b, "Role rows", len(role_df))
    metric_card(c, "Exception rows", len(exception_df))
    metric_card(d, "Draft status rows", len(status_df))

    st.subheader("Draft status")
    st.dataframe(status_df, use_container_width=True)

    st.subheader("System-owner request results")
    st.dataframe(draft_df, use_container_width=True) if not draft_df.empty else st.info("No owner-mapped requests found.")

    st.subheader("Role results")
    st.dataframe(role_df, use_container_width=True) if not role_df.empty else st.info("No matching roles found.")

    st.subheader("Exceptions")
    st.dataframe(exception_df, use_container_width=True) if not exception_df.empty else st.success("No exceptions found.")

    if show_debug:
        with st.expander("Debug details", expanded=False):
            st.write("pythoncom available:", pythoncom is not None)
            st.write("win32 available:", win32 is not None)
            st.write("Owners columns:", list(owners_df.columns))
            st.write("Onboarding columns:", list(onboarding_df.columns))
            st.write("Role columns:", list(roles_df.columns))
            st.write("Desired columns:", list(desired_df.columns) if not desired_df.empty else [])
            st.write("Owner emails:", sorted(draft_df["owner email"].dropna().astype(str).unique()) if not draft_df.empty else [])
            st.write("Systems:", sorted(draft_df["system"].dropna().astype(str).unique()) if not draft_df.empty else [])
