# this script create for demo purpose only with approved AI tools , should not be use for client demo.
# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: script.py

import os
import re
import pandas as pd
import win32com.client as win32

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

ONBOARDING_FILE = os.path.join(BASE_DIR, "Contractor_Onboarding_form.xlsx")
SYSTEM_OWNER_FILE = os.path.join(BASE_DIR, "System_owner_list.xlsx")
ROLE_FILE = os.path.join(BASE_DIR, "Role_consolidated_list.xlsx")
DESIRED_FILE = os.path.join(BASE_DIR, "Desired_outocme.xlsx")

OUTPUT_REQUESTS = os.path.join(BASE_DIR, "request_exceptions.xlsx")
OUTPUT_ROLES = os.path.join(BASE_DIR, "role_results.xlsx")

def clean_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip()

def split_systems(value):
    if pd.isna(value):
        return []
    parts = re.split(r"[,\n;]+", str(value))
    return [p.strip() for p in parts if p.strip()]

def load_data():
    onboarding = pd.read_excel(ONBOARDING_FILE)
    system_owner = pd.read_excel(SYSTEM_OWNER_FILE)
    role = pd.read_excel(ROLE_FILE)
    desired = pd.read_excel(DESIRED_FILE)
    return onboarding, system_owner, role, desired

def build_system_owner_lookup(system_owner_df):
    system_owner_df = system_owner_df.copy()
    system_owner_df.columns = [c.strip() for c in system_owner_df.columns]
    lookup = {}
    for _, row in system_owner_df.iterrows():
        system_id = clean_text(row.get("system id")).upper()
        approver = clean_text(row.get("Approver"))
        approver_id = clean_text(row.get("Approver id"))
        if system_id:
            lookup[system_id] = {"Approver": approver, "Approver id": approver_id}
    return lookup

def build_role_lookup(role_df):
    role_df = role_df.copy()
    role_df.columns = [c.strip() for c in role_df.columns]
    lookup = {}
    for _, row in role_df.iterrows():
        team = clean_text(row.get("Team")).upper()
        system = clean_text(row.get("System")).upper()
        role_type = clean_text(row.get("Role Type")).upper()
        role_name = clean_text(row.get("Role Name"))
        role_desc = clean_text(row.get("Role Description"))
        key = (team, system)
        lookup.setdefault(key, []).append({
            "Role Type": role_type,
            "Role Name": role_name,
            "Role Description": role_desc,
        })
    return lookup

def generate_outputs(onboarding_df, system_lookup, role_lookup):
    onboarding_df = onboarding_df.copy()
    onboarding_df.columns = [c.strip() for c in onboarding_df.columns]

    exceptions = []
    role_rows = []

    for idx, row in onboarding_df.iterrows():
        contractor = clean_text(row.get("Contractor Name"))
        contractor_email = clean_text(row.get("Contractor Email"))
        manager_name = clean_text(row.get("Manager Name"))
        manager_email = clean_text(row.get("Manager Email"))
        team = clean_text(row.get("Team")).upper()
        start_date = row.get("Start Date")
        end_date = row.get("End Date")
        requested_systems = split_systems(row.get("Requested Systems"))
        request_id = clean_text(row.get("Request ID"))
        justification = clean_text(row.get("Business Justification"))

        if not request_id:
            exceptions.append({
                "Row": idx + 2,
                "Contractor Name": contractor,
                "Issue": "Missing Request ID"
            })

        for system in requested_systems:
            owner = system_lookup.get(system.upper())
            if not owner:
                exceptions.append({
                    "Row": idx + 2,
                    "Contractor Name": contractor,
                    "Issue": f"Unknown system: {system}"
                })
                continue

            role_matches = role_lookup.get((team, system.upper()), [])
            if not role_matches:
                exceptions.append({
                    "Row": idx + 2,
                    "Contractor Name": contractor,
                    "Issue": f"No role mapping for Team={team}, System={system}"
                })

            for role_match in role_matches:
                role_rows.append({
                    "Contractor Name": contractor,
                    "Contractor Email": contractor_email,
                    "Manager Name": manager_name,
                    "Manager Email": manager_email,
                    "Team": team,
                    "Start Date": start_date,
                    "End Date": end_date,
                    "Requested System": system,
                    "Request ID": request_id,
                    "Business Justification": justification,
                    "Approver": owner["Approver"],
                    "Approver id": owner["Approver id"],
                    "Role Type": role_match["Role Type"],
                    "Role Name": role_match["Role Name"],
                    "Role Description": role_match["Role Description"],
                })

    exceptions_df = pd.DataFrame(exceptions)
    role_results_df = pd.DataFrame(role_rows)

    exceptions_df.to_excel(OUTPUT_REQUESTS, index=False)
    role_results_df.to_excel(OUTPUT_ROLES, index=False)

    return exceptions_df, role_results_df

def create_outlook_draft(to_email, subject, body, attachment_paths):
    outlook = win32.Dispatch("Outlook.Application")
    mail = outlook.CreateItem(0)
    mail.To = to_email
    mail.Subject = subject
    mail.Body = body

    for file_path in attachment_paths:
        if file_path and os.path.exists(file_path):
            mail.Attachments.Add(file_path)
        else:
            print(f"Skipped missing attachment: {file_path}")

    mail.Save()
    return mail

def main():
    onboarding_df, system_df, role_df, desired_df = load_data()
    system_lookup = build_system_owner_lookup(system_df)
    role_lookup = build_role_lookup(role_df)

    exceptions_df, role_results_df = generate_outputs(onboarding_df, system_lookup, role_lookup)

    contractor_email = clean_text(onboarding_df.loc[0, "Contractor Email"]) if not onboarding_df.empty else ""
    manager_email = clean_text(onboarding_df.loc[0, "Manager Email"]) if not onboarding_df.empty else ""

    draft_to = manager_email or contractor_email
    draft_subject = "Contractor onboarding outputs"
    draft_body = (
        "Hi,\n\n"
        "Please find the generated onboarding outputs attached.\n\n"
        f"- Exceptions file: {os.path.basename(OUTPUT_REQUESTS)}\n"
        f"- Role results file: {os.path.basename(OUTPUT_ROLES)}\n\n"
        "Thanks."
    )

    create_outlook_draft(
        draft_to,
        draft_subject,
        draft_body,
        [OUTPUT_REQUESTS, OUTPUT_ROLES]
    )

    print("Done. Output files created and Outlook draft saved.")

if __name__ == "__main__":
    main()
